---
- name: Preflight - Fail if target host is not stable for this Role.
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in webserver_stable_os)

- name: Include OS family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Populate Service Facts.
  service_facts:

- name: Set Fact Webserver.
  set_fact:
    webserver_name: "{% if 'apache2.service' in services %}apache{% elif 'httpd.service' in services %}apache{% elif 'nginx.service' in services %}nginx{% else %}none{% endif %}"
